# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

workspace:
    base: /build
    path: src

pipeline:
    build:
        image: docker
        commands:
            - docker build -t korigod/toldyou:latest toldyou
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    publish:
        image: docker
        secrets:
            - source: docker_username
              target: DOCKER_USERNAME
            - source: docker_password
              target: DOCKER_PASSWORD
        commands:
            - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            - docker push korigod/toldyou:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    deploy:
        image: docker
        commands:
            - docker pull korigod/toldyou
            - docker stack deploy --with-registry-auth -c docker-compose.yml toldyou
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /packages/toldyou/toldyou/envs:/build/src/toldyou/envs:ro
            - /packages/toldyou/mongo/envs:/build/src/mongo/envs:ro
