# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

version: '3'
services:
    toldyou:
        image: korigod/toldyou:latest
        env_file: toldyou/envs
        depends_on:
            - mongo
    mongo:
        image: mongo:4.0.0-xenial
        env_file: mongo/envs
        environment:
            - MONGO_DATA_DIR=/data/db
        volumes:
            - /packages/toldyou/mongo/data:/data/db
