# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

version: '3'
services:
    toldyou:
        image: toldyou:latest
        env_file: toldyou/envs
        restart: always
        links:
            - mongo
        depends_on:
            - mongo
    mongo:
        image: mongo:4.0.0-xenial
        env_file: mongo/envs
        restart: always
        environment:
            - MONGO_DATA_DIR=/data/db
        ports:
            - 127.0.0.1:27017:27017
        volumes:
            - ./mongo/data:/data/db
